### PR TITLE
fix: scripts section gets removed from package.json

### LINKED ISSUE #203: scripts section is missing from package.json
Compare project created by Angular Console and Angular CLI. I found that scripts section is missing if the project is created by Angular Console. It seems the `@schematics/angular` that include in Angular Console is different than Github version.

image

### PR DESCRIPTION
**Pull request by vsavkin**
Closes #203

### CODE REVIEW

File: package-scripts.js [hunk 1]
```diff
@@ -86,7 +86,7 @@ module.exports = {
       'clean': 'if exist dist rmdir dist /s /q',
       'compile': 'tsc -p server/tsconfig.json',
       'copy-assets': 'copy server\\package.json dist\\server\\package.json && (robocopy server\\assets dist\\server\\assets /e || echo 0)',
-      'install-node-modules': 'cd dist\\electron && yarn',
+      'install-node-modules': 'cd dist\\server && yarn',
```
Comment (mrmeku) [inline package-scripts.js]: Just making sure, was this intentional? It seems unrelated

Comment (vsavkin) [reply package-scripts.js]: Yup. It's intentional.
